# Generated by Django 4.0.4 on 2022-04-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plato', '0002_plato_categoria_plato_tiempo_preparaciona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.IntegerField(primary_key=1, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plato.alimento'),
        ),
    ]
